name: Build & Release

on:
  workflow_dispatch:        # Allow manual triggering
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write
  pull-requests: write
  packages: write
  issues: write

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.DOCKERHUB_TAG }}
  PROJECT_TYPE: simple

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Release Please (main branch only)
        id: rp
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: ${{ env.PROJECT_TYPE }}

      - name: Docker Logins (Docker Hub & GHCR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker Tags
        id: tags
        run: |
          if [[ "${{ steps.rp.outputs.release_created }}" == "true" ]]; then
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "type=semver,pattern={{version}},value=v${{ steps.rp.outputs.major }}.${{ steps.rp.outputs.minor }}.${{ steps.rp.outputs.patch }}" >> $GITHUB_OUTPUT
            echo "type=ref,event=branch,value=main" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "tags<<EOF" >> $GITHUB_OUTPUT
            echo "type=ref,event=branch" >> $GITHUB_OUTPUT
            echo "type=ref,event=pr" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            ghcr.io/Nexunaut/wallos
          tags: ${{ steps.tags.outputs.tags }}

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
